language: java
jdk:
- openjdk8
after_success: chmod +x tool-model.py && ./tool-model.py
before_install:
- openssl aes-256-cbc -K $encrypted_bf6b523e6bb0_key -iv $encrypted_bf6b523e6bb0_iv
  -in id_rsa_travis.enc -out id_rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa_travis
- ssh-add id_rsa_travis
